/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package memory.game;

import memory.game.view.HomePage;

public class App {
    public static void main(String[] args) {
        new HomePage();
        new App();
    }
}